<?php

/**
* @file
* Removes some links from teasers.
*
*/

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Node\NodeInterface;

/**
 * Implements hook_help().
 */
function fixteaserlinks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.fixteaserlinks':
      $output = '<p>' . t('The “Fix teaserlink” module is a simple module that removes some links from teasers.  See README.md for details') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_node_links_alter().
 */
function fixteaserlinks_node_links_alter(array &$links, NodeInterface $entity, array &$context) {
  if ('teaser' == $context['view_mode']) {
    if (\Drupal::config('fixteaserlinks.settings')->get('fixteaserlinks_comment')) {
      // remove "add comment" or "log in ... to comment" link from node teaser mode display
      unset($links['comment__comment']);
    }
    // Get rid of "read more" as well.
    if (\Drupal::config('fixteaserlinks.settings')->get('fixteaserlinks_readmore')) {
      unset($links['node']['#links']['node-readmore']);
    }
  }
}
